version: '3'

services:
  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "8080:8080"
    environment:
      API_HOST: "backend"
      API_PORT: 3000
    links:
      - backend
    # depends_on:
    #   - backend
    # expose:
      # - 8080

  backend:
    container_name: backend
    environment:
      PORT: 3001
      POSTGRES_PORT: 5432
      POSTGRES_HOST: "database"
      POSTGRES_DB: "main_db"
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "secret"
    build: ./backend
    ports:
      - 3000:3000
    links:
      - database
    depends_on:
      - database
    # entrypoint: ["bash -c","curl -X POST 'localhost:3000/user'", "-H", '"Content-Type: application/json"', "-d", "'{\"login\": \"guest\", \"password\": 123}'"] 
  database:
    container_name: database
    environment:
      POSTGRES_DB: "main_db"
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "secret"
    build: ./database
    ports:
      - 5432:5432
    expose:
      - 5432
    command: -p 5432