version: '3'

services:
  frontend:
    build: ./frontend
    container_name: frontend
    environment:
      API_HOST: "localhost"
      API_PORT: 3000
    ports:
      - "8080:8080"
    links:
      - backend
    depends_on:
      - backend
    # expose:
      # - 8080

  backend:
    container_name: backend
    environment:
      PORT: 3000
      POSTGRES_PORT: 5432
      POSTGRES_HOST: "database"
      POSTGRES_DB: "main_db"
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "secret"
    build: ./backend
    ports:
      - 3000:3000
    links:
      - database
    depends_on:
      - database
  database:
    container_name: database
    environment:
      POSTGRES_DB: "main_db"
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "secret"
    build: ./database
    ports:
      - 5432:5432
    expose:
      - 5432
    command: -p 5432
