version: '3'

services:
  frontend:
    image: urls_frontend:v1.0
    build: ./frontend
    ports:
      - "8080:8080"
  #   volumes:
  #     - .:/usr/src/frontend/
  backend:
    image: urls_backend:v1.0
    environment:
      PORT: 3000
    build: ./backend
    ports:
      - "3000:3000"
  database:
    image: urls_database:v1.0
    environment:
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "secret"
    build: ./database
    ports:
      - "5432:5432"